id: P004577
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19200
  title: ཤེས་བརྩོན་གྱི་སྟོབས།
  author: ''
  volumes:
    d36fdbcf9d014f44aa8fe557142f895d:
      image_group_id: I2PD19213
      title: ''
      volume_number: 1
      total_pages: 206
      base_file: v001.txt
